name: Build and Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Select Xcode 11.4
      run: sudo xcode-select -s /Applications/Xcode_11.4.app && xcodebuild -version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v